/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  displayOrder: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type RentalPackage = {
  _id: string;
  _type: "rentalPackage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  category:
    | "Presentation"
    | "Wedding"
    | "Live Music"
    | "Lighting"
    | "Party"
    | "Sound"
    | "Custom";
  description: string;
  bestFor: string;
  eventSize: string;
  includes: Array<string>;
  addons: Array<string>;
  rentalPeriod?: string;
  featured: boolean;
  displayOrder: number;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Faq
  | SanityImageAssetReference
  | RentalPackage
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/content/sanity/queries.ts
// Variable: rentalPackagesQuery
// Query: *[  _type == "rentalPackage"] | order(displayOrder asc, name asc) {  _id,  "slug": slug.current,  name,  category,  description,  bestFor,  eventSize,  includes,  addons,  rentalPeriod,  featured,  displayOrder,  image {    alt,    asset,    crop,    hotspot  }}
export type RentalPackagesQueryResult = Array<{
  _id: string;
  slug: string;
  name: string;
  category:
    | "Custom"
    | "Lighting"
    | "Live Music"
    | "Party"
    | "Presentation"
    | "Sound"
    | "Wedding";
  description: string;
  bestFor: string;
  eventSize: string;
  includes: Array<string>;
  addons: Array<string>;
  rentalPeriod: string | null;
  featured: boolean;
  displayOrder: number;
  image: {
    alt: string;
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  };
}>;

// Source: src/content/sanity/queries.ts
// Variable: faqsQuery
// Query: *[  _type == "faq"] | order(displayOrder asc, question asc) {  _id,  question,  answer,  displayOrder}
export type FaqsQueryResult = Array<{
  _id: string;
  question: string;
  answer: string;
  displayOrder: number;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "rentalPackage"\n] | order(displayOrder asc, name asc) {\n  _id,\n  "slug": slug.current,\n  name,\n  category,\n  description,\n  bestFor,\n  eventSize,\n  includes,\n  addons,\n  rentalPeriod,\n  featured,\n  displayOrder,\n  image {\n    alt,\n    asset,\n    crop,\n    hotspot\n  }\n}': RentalPackagesQueryResult;
    '*[\n  _type == "faq"\n] | order(displayOrder asc, question asc) {\n  _id,\n  question,\n  answer,\n  displayOrder\n}': FaqsQueryResult;
  }
}
